spring:
  application:
    name: customer-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/customerdb
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9010
  error:
    include-message: always
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
